"""Build the global ``data/wiki/INDEX.md`` table of contents.

INDEX.md is an auto-generated artifact, idempotent for a given wiki state.
The CLI (``kb-wiki-index``) writes it; ``kb-lint-wiki`` asserts it is in sync.
"""

from __future__ import annotations

from datetime import date
from pathlib import Path

from kb_mcp.cli.wiki.utils import parse_frontmatter

INDEX_FILENAME = "INDEX.md"
INDEX_STEM = "INDEX"

# Section title → top-level wiki dirname. Order = render order in INDEX.md.
CATEGORIES: tuple[tuple[str, str], ...] = (
    ("Entities", "entities"),
    ("Concepts", "concepts"),
    ("Decisions", "decisions"),
    ("Questions", "questions"),
    ("Improvements", "improvements"),
    ("Checklists", "checklists"),
    ("Summaries", "summaries"),
)


def _page_date(path: Path, fm: dict | None) -> str:
    """YYYY-MM-DD for sort/display: fm.updated → fm.created → file mtime."""
    if fm:
        for key in ("updated", "created"):
            val = fm.get(key)
            if val:
                s = str(val).strip()
                if len(s) >= 10:
                    return s[:10]
    return date.fromtimestamp(path.stat().st_mtime).isoformat()


def _scan_pages(root: Path) -> list[tuple[Path, dict | None]]:
    """Walk root for *.md, skipping per-subject _index.md hubs."""
    if not root.exists():
        return []
    out: list[tuple[Path, dict | None]] = []
    for f in sorted(root.rglob("*.md")):
        if f.name == "_index.md":
            continue
        fm = parse_frontmatter(f.read_text())
        out.append((f, fm))
    return out


def _render_entries(pages: list[tuple[Path, dict | None]]) -> list[str]:
    """Newest first. Format: ``- [[stem]] — YYYY-MM-DD``."""
    rows = sorted(pages, key=lambda pf: (_page_date(*pf), pf[0].stem), reverse=True)
    return [f"- [[{f.stem}]] — {_page_date(f, fm)}" for f, fm in rows]


def _render_section(
    title: str,
    pages: list[tuple[Path, dict | None]],
    wiki_dir: Path,
) -> list[str]:
    """Render ``## <Title>`` block. Entities and Summaries get sub-grouping."""
    lines = [f"## {title}", ""]
    if not pages:
        lines.extend(["(none)", ""])
        return lines

    group_root: Path | None = None
    if title == "Entities":
        group_root = wiki_dir / "entities"
    elif title == "Summaries":
        group_root = wiki_dir / "summaries"

    if group_root is None:
        lines.extend(_render_entries(pages))
        lines.append("")
        return lines

    groups: dict[str, list[tuple[Path, dict | None]]] = {}
    for f, fm in pages:
        bucket = f.relative_to(group_root).parts[0]
        groups.setdefault(bucket, []).append((f, fm))
    for bucket in sorted(groups):
        lines.append(f"### {bucket}")
        lines.append("")
        lines.extend(_render_entries(groups[bucket]))
        lines.append("")
    return lines


def build_index(wiki_dir: Path) -> str:
    """Return the full INDEX.md content (frontmatter + body).

    Deterministic for a given wiki state — ``created`` is the earliest page
    date, ``updated`` the latest; both are derived from page frontmatter so
    re-running the generator on unchanged content yields the same bytes.
    """
    sections = {title: _scan_pages(wiki_dir / dirname) for title, dirname in CATEGORIES}

    all_pages = [p for ps in sections.values() for p in ps]
    if all_pages:
        dates = sorted(_page_date(f, fm) for f, fm in all_pages)
        created, updated = dates[0], dates[-1]
    else:
        today = date.today().isoformat()
        created = updated = today

    out: list[str] = [
        "---",
        "type: index",
        f"created: {created}",
        f"updated: {updated}",
        "---",
        "",
        "# Wiki Index",
        "",
        "Auto-generated by `kb-wiki-index`. Do not edit by hand — regenerate after adding pages.",
        "",
    ]
    for title, _ in CATEGORIES:
        out.extend(_render_section(title, sections[title], wiki_dir))
    return "\n".join(out).rstrip() + "\n"
