"""add canonical memory tables

Revision ID: b72b13e7c9a1
Revises: 53cdbd2e163d
Create Date: 2026-06-04 10:30:00.000000

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op

revision: str = "b72b13e7c9a1"
down_revision: Union[str, Sequence[str], None] = "53cdbd2e163d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _upgrade_postgresql() -> None:
    op.execute(
        """
        CREATE TABLE pages (
            id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            slug            TEXT NOT NULL UNIQUE,
            title           TEXT NOT NULL,
            type            TEXT NOT NULL
                            CHECK (type IN ('entity','concept','decision','question','improvement','checklist','summary')),
            category        TEXT,
            review_status   TEXT NOT NULL
                            CHECK (review_status IN ('not_processed','pending_for_approve','approved','rejected')),
            origin          TEXT NOT NULL DEFAULT 'ingested'
                            CHECK (origin IN ('ingested','authored','imported')),
            body_md         TEXT NOT NULL,
            frontmatter     JSONB NOT NULL,
            export_path     TEXT UNIQUE,
            created_at      TEXT NOT NULL
                            CHECK (created_at LIKE '____-__-__T__:__:__+09:00'),
            updated_at      TEXT NOT NULL
                            CHECK (updated_at LIKE '____-__-__T__:__:__+09:00')
        )
        """
    )
    op.execute(
        "CREATE INDEX ix_pages_review_status_updated_at "
        "ON pages(review_status, updated_at DESC)"
    )
    op.execute("CREATE INDEX ix_pages_type_category ON pages(type, category)")

    op.execute(
        """
        CREATE TABLE raw_sources (
            id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source_key      TEXT NOT NULL UNIQUE,
            source_type     TEXT NOT NULL,
            source_url      TEXT,
            title           TEXT,
            content_md      TEXT NOT NULL,
            frontmatter     JSONB NOT NULL,
            captured_at     TEXT,
            created_at      TEXT NOT NULL
                            CHECK (created_at LIKE '____-__-__T__:__:__+09:00')
        )
        """
    )
    op.execute(
        "CREATE INDEX ix_raw_sources_type_captured_at "
        "ON raw_sources(source_type, captured_at DESC)"
    )
    op.execute(
        """
        CREATE OR REPLACE FUNCTION prevent_raw_sources_update()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            RAISE EXCEPTION 'raw_sources is append-only';
        END;
        $$;
        """
    )
    op.execute(
        """
        CREATE OR REPLACE FUNCTION prevent_raw_sources_delete()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            RAISE EXCEPTION 'raw_sources is append-only';
        END;
        $$;
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_raw_sources_no_update
        BEFORE UPDATE ON raw_sources
        FOR EACH ROW EXECUTE FUNCTION prevent_raw_sources_update()
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_raw_sources_no_delete
        BEFORE DELETE ON raw_sources
        FOR EACH ROW EXECUTE FUNCTION prevent_raw_sources_delete()
        """
    )

    op.execute(
        """
        CREATE TABLE page_sources (
            id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            page_id         INTEGER NOT NULL REFERENCES pages(id) ON DELETE CASCADE,
            raw_source_id   INTEGER REFERENCES raw_sources(id) ON DELETE RESTRICT,
            citation_path   TEXT NOT NULL,
            created_at      TEXT NOT NULL
                            CHECK (created_at LIKE '____-__-__T__:__:__+09:00'),
            UNIQUE (page_id, citation_path)
        )
        """
    )
    op.execute("CREATE INDEX ix_page_sources_page_id ON page_sources(page_id)")
    op.execute(
        "CREATE INDEX ix_page_sources_raw_source_id ON page_sources(raw_source_id)"
    )

    op.execute(
        """
        CREATE TABLE page_revisions (
            id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            page_id         INTEGER NOT NULL REFERENCES pages(id) ON DELETE CASCADE,
            revision_number INTEGER NOT NULL,
            change_kind     TEXT NOT NULL
                            CHECK (change_kind IN ('import','create','update','approve','reject','export')),
            body_md         TEXT NOT NULL,
            frontmatter     JSONB NOT NULL,
            changed_fields  JSONB,
            created_at      TEXT NOT NULL
                            CHECK (created_at LIKE '____-__-__T__:__:__+09:00'),
            source          TEXT NOT NULL DEFAULT 'migration'
                            CHECK (source IN ('migration','console','agent','system')),
            note            TEXT,
            UNIQUE (page_id, revision_number)
        )
        """
    )
    op.execute(
        "CREATE INDEX ix_page_revisions_page_id_created_at "
        "ON page_revisions(page_id, created_at DESC)"
    )
    op.execute(
        """
        CREATE OR REPLACE FUNCTION prevent_page_revisions_update()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            RAISE EXCEPTION 'page_revisions is append-only';
        END;
        $$;
        """
    )
    op.execute(
        """
        CREATE OR REPLACE FUNCTION prevent_page_revisions_delete()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            RAISE EXCEPTION 'page_revisions is append-only';
        END;
        $$;
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_page_revisions_no_update
        BEFORE UPDATE ON page_revisions
        FOR EACH ROW EXECUTE FUNCTION prevent_page_revisions_update()
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_page_revisions_no_delete
        BEFORE DELETE ON page_revisions
        FOR EACH ROW EXECUTE FUNCTION prevent_page_revisions_delete()
        """
    )


def upgrade() -> None:
    """Create DB-canonical pages, sources, citations, and revisions."""
    if op.get_bind().dialect.name == "postgresql":
        _upgrade_postgresql()
        return

    op.execute(
        """
        CREATE TABLE pages (
            id              INTEGER PRIMARY KEY,
            slug            TEXT NOT NULL UNIQUE,
            title           TEXT NOT NULL,
            type            TEXT NOT NULL
                            CHECK (type IN ('entity','concept','decision','question','improvement','checklist','summary')),
            category        TEXT,
            review_status   TEXT NOT NULL
                            CHECK (review_status IN ('not_processed','pending_for_approve','approved','rejected')),
            origin          TEXT NOT NULL DEFAULT 'ingested'
                            CHECK (origin IN ('ingested','authored','imported')),
            body_md         TEXT NOT NULL,
            frontmatter     JSON NOT NULL CHECK (json_valid(frontmatter)),
            export_path     TEXT UNIQUE,
            created_at      TEXT NOT NULL
                            CHECK (created_at LIKE '____-__-__T__:__:__+09:00'),
            updated_at      TEXT NOT NULL
                            CHECK (updated_at LIKE '____-__-__T__:__:__+09:00')
        )
        """
    )
    op.execute(
        "CREATE INDEX ix_pages_review_status_updated_at "
        "ON pages(review_status, updated_at DESC)"
    )
    op.execute("CREATE INDEX ix_pages_type_category ON pages(type, category)")

    op.execute(
        """
        CREATE TABLE raw_sources (
            id              INTEGER PRIMARY KEY,
            source_key      TEXT NOT NULL UNIQUE,
            source_type     TEXT NOT NULL,
            source_url      TEXT,
            title           TEXT,
            content_md      TEXT NOT NULL,
            frontmatter     JSON NOT NULL CHECK (json_valid(frontmatter)),
            captured_at     TEXT,
            created_at      TEXT NOT NULL
                            CHECK (created_at LIKE '____-__-__T__:__:__+09:00')
        )
        """
    )
    op.execute(
        "CREATE INDEX ix_raw_sources_type_captured_at "
        "ON raw_sources(source_type, captured_at DESC)"
    )
    op.execute(
        """
        CREATE TRIGGER trg_raw_sources_no_update
        BEFORE UPDATE ON raw_sources
        BEGIN SELECT RAISE(ABORT, 'raw_sources is append-only'); END
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_raw_sources_no_delete
        BEFORE DELETE ON raw_sources
        BEGIN SELECT RAISE(ABORT, 'raw_sources is append-only'); END
        """
    )

    op.execute(
        """
        CREATE TABLE page_sources (
            id              INTEGER PRIMARY KEY,
            page_id         INTEGER NOT NULL REFERENCES pages(id) ON DELETE CASCADE,
            raw_source_id   INTEGER REFERENCES raw_sources(id) ON DELETE RESTRICT,
            citation_path   TEXT NOT NULL,
            created_at      TEXT NOT NULL
                            CHECK (created_at LIKE '____-__-__T__:__:__+09:00'),
            UNIQUE (page_id, citation_path)
        )
        """
    )
    op.execute("CREATE INDEX ix_page_sources_page_id ON page_sources(page_id)")
    op.execute(
        "CREATE INDEX ix_page_sources_raw_source_id ON page_sources(raw_source_id)"
    )

    op.execute(
        """
        CREATE TABLE page_revisions (
            id              INTEGER PRIMARY KEY,
            page_id         INTEGER NOT NULL REFERENCES pages(id) ON DELETE CASCADE,
            revision_number INTEGER NOT NULL,
            change_kind     TEXT NOT NULL
                            CHECK (change_kind IN ('import','create','update','approve','reject','export')),
            body_md         TEXT NOT NULL,
            frontmatter     JSON NOT NULL CHECK (json_valid(frontmatter)),
            changed_fields  JSON CHECK (changed_fields IS NULL OR json_valid(changed_fields)),
            created_at      TEXT NOT NULL
                            CHECK (created_at LIKE '____-__-__T__:__:__+09:00'),
            source          TEXT NOT NULL DEFAULT 'migration'
                            CHECK (source IN ('migration','console','agent','system')),
            note            TEXT,
            UNIQUE (page_id, revision_number)
        )
        """
    )
    op.execute(
        "CREATE INDEX ix_page_revisions_page_id_created_at "
        "ON page_revisions(page_id, created_at DESC)"
    )
    op.execute(
        """
        CREATE TRIGGER trg_page_revisions_no_update
        BEFORE UPDATE ON page_revisions
        BEGIN SELECT RAISE(ABORT, 'page_revisions is append-only'); END
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_page_revisions_no_delete
        BEFORE DELETE ON page_revisions
        BEGIN SELECT RAISE(ABORT, 'page_revisions is append-only'); END
        """
    )


def downgrade() -> None:
    """Drop canonical memory tables."""
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP TABLE IF EXISTS page_revisions")
        op.execute("DROP TABLE IF EXISTS page_sources")
        op.execute("DROP TABLE IF EXISTS raw_sources")
        op.execute("DROP TABLE IF EXISTS pages")
        op.execute("DROP FUNCTION IF EXISTS prevent_page_revisions_update()")
        op.execute("DROP FUNCTION IF EXISTS prevent_page_revisions_delete()")
        op.execute("DROP FUNCTION IF EXISTS prevent_raw_sources_update()")
        op.execute("DROP FUNCTION IF EXISTS prevent_raw_sources_delete()")
        return

    op.execute("DROP TABLE IF EXISTS page_revisions")
    op.execute("DROP TABLE IF EXISTS page_sources")
    op.execute("DROP TABLE IF EXISTS raw_sources")
    op.execute("DROP TABLE IF EXISTS pages")
